### ISSUE TITLE
Guardar Contacto

### ISSUE THREAD

**Issue by sergiosanabria** [usinapim/radar-cultural-backend#6]
Crear un metodo que guarde los datos del Contacto
metodo: POST
data:  JSON coon los siguientes atributos
- nombre
- apellido
- email
- mensaje 

respuesta
- 200 si es OK
- 400 si es ERROR

**Comment by matudelatower** [comment]
Como es el cuerpo del mensaje que me vas a enviar?

**Comment by matudelatower** [comment]
El cuerpo debe tener este formato:

``` json
{
  "nombre": "haha",
  "apellido": "otro",
  "email": "nada@nada.com",
  "mensaje": "atutu"
}
```

La respuesta deberia ser solamente 200 o 400, o puede ir en el status code?
